project/journey_blog/urls.py
from django.conf.urls import url
from journey_blog.views import JourneyListView, JourneyCreateView, JourneyUpdateView, JourneyDetailView

urlpatterns = [
    url(r'^$', JourneyListView.as_view(), name='journey_list'),
    url(r'^login/$', "django.contrib.auth.views.login", name='journey_login'),
    url(r'^create/$', JourneyCreateView.as_view(), name='journey_create'),
    url(r'^update/(?P<pk>[0-9]+)/$', JourneyUpdateView.as_view(), name='journey_update'),
    url(r'^update/(?P<pk>[0-9]+)/(?P<destination_pk>[0-9]+)/$', JourneyUpdateView.as_view(), name='journey_update_destination'),
    url(r'^detail/(?P<pk>[0-9]+)/$', JourneyDetailView.as_view(), name='journey_detail'),
    url(r'^detail/(?P<pk>[0-9]+)/(?P<destination_pk>[0-9]+)/$', JourneyDetailView.as_view(), name='journey_detail_destination'),
]

project/project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView


urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='project/about.html'), name='about'),
    url(r'^tips-tricks/', TemplateView.as_view(template_name='project/tips_tricks.html'), name='tips_tricks'),
    url(r'^experience/', TemplateView.as_view(template_name='project/experience.html'), name='experience'),
    url(r'^journeys/', include('journey_blog.urls')),
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
)

project/journey_blog/models.py
from ckeditor.fields import RichTextField
from django.core.urlresolvers import reverse_lazy
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


TYPE_TRAIN = "train"
TYPE_BUS = "bus"
TYPE_BOAT = "boat"

TRAVEL_TYPE_CHOICES = (
    (TYPE_TRAIN, _("Train")),
    (TYPE_BUS, _("Bus")),
    (TYPE_BOAT, _("Boat")),
)

# UNPUBLISHED
# PUBLISHED
# DRAFT

class JourneyTravelType(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Name"))

    def __unicode__(self):
        return self.name

    class Meta():
        verbose_name = _("Journey Travel Type")
        verbose_name_plural = _("Journey Travel Types")
        ordering = ["pk"]


class JourneyDestination(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Destination"))
    content = RichTextField(verbose_name=_("Content"), blank=True, null=True, config_name="destination_editor")
    draft = RichTextField(verbose_name=_("Draft"), blank=True, null=True)
    types = models.ManyToManyField(JourneyTravelType, verbose_name=_("Typ"))

    def __unicode__(self):
        return self.name

    class Meta():
        verbose_name = _("Journey Destination")
        verbose_name_plural = _("Journey Destinations")
        ordering = ["id"]


class Journey(models.Model):
    title = models.CharField(max_length=255, verbose_name=_("Title"))
    destinations = models.ManyToManyField(JourneyDestination, verbose_name=_("Destinations"), blank=True, null=True)
    author = models.ForeignKey(User, verbose_name=_("Author"), null=True, blank=True)
    description = models.TextField(verbose_name=_("Description"))
    published = models.BooleanField(verbose_name=_("Published"), default=False)
    cdate = models.DateTimeField(auto_now_add=True)
    mdate = models.DateTimeField(auto_now=True)

    def get_absolute_url(self, destination=False):
        if not destination:
            new_destination = self.destinations.last()
        else:
            new_destination = self.destinations.get(pk=destination)
        if new_destination:
            return reverse_lazy("journey_update_destination", kwargs={
                'pk': self.pk,
                'destination_pk': new_destination.pk,
            })
        else:
            return reverse_lazy("journey_update", kwargs={
                'pk': self.pk,
            })

    def __unicode__(self):
        return self.title

    class Meta():
        verbose_name = _("Journey")
        verbose_name_plural = _("Journeys")
        ordering = ["-cdate"]

project/journey_blog/forms.py
from django import forms
from django.forms.models import ModelForm
from journey_blog.models import JourneyDestination, JourneyTravelType, Journey


class JourneyForm(ModelForm):

    class Meta:
        model = Journey


class JourneyAddDestinationForm(ModelForm):
    types = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), queryset=JourneyTravelType.objects.all())

    class Meta:
        model = JourneyDestination

project/journey_blog/views.py
from django.contrib.auth.models import User
from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from journey_blog.forms import JourneyAddDestinationForm, JourneyForm
from journey_blog.models import Journey, TYPE_TRAIN, TYPE_BUS, TYPE_BOAT, JourneyDestination, JourneyTravelType


class JourneyListView(ListView):
    model = Journey
    template_name = "journey_blog/journey/list.html"
    context_object_name = "journeys"


class JourneyCreateView(CreateView):
    model = Journey
    template_name = "journey_blog/journey/create.html"
    form_class = JourneyForm

    def form_valid(self, form):
        journey = form.save(commit=False)
        journey.author = User.objects.get(pk=1)
        journey.save()
        return super(JourneyCreateView, self).form_valid(form)


class JourneyUpdateView(UpdateView):
    model = Journey
    template_name = "journey_blog/journey/update.html"
    form_class = JourneyAddDestinationForm
    context_object_name = "journey"

    def form_valid(self, form):
        content = self.request.POST.get("content", False)
        published = self.request.POST.get("published", False)
        journey = Journey.objects.get(pk=self.kwargs["pk"])
        if published:
            journey.published = True
        if content != False:
            if self.kwargs.get("destination_pk", False):
                destination = JourneyDestination.objects.get(pk=self.kwargs["destination_pk"])
            else:
                destination = Journey.destinations.first()
            destination.content = content
            destination.save()
            journey.save()
        else:
            name = self.request.POST.get("name", None)
            types = self.request.POST.getlist('types')
            destination = JourneyDestination.objects.create(name=name)
            destination.types.add(*types)
            journey.destinations.add(destination)
            journey.save()
        if published:
            return redirect(reverse_lazy("journey_list"))
        return super(JourneyUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(JourneyUpdateView, self).get_context_data(**kwargs)
        destination_pk = self.kwargs.get("destination_pk", False)
        if destination_pk:
            selected_destination = JourneyDestination.objects.get(pk=destination_pk)
        elif self.object.destinations.count() > 0:
            selected_destination = self.object.destinations.first()
        else:
            selected_destination = False
        if selected_destination:
            context.update({
                "selected_destination": selected_destination,
                "content_form": self.form_class(instance=selected_destination)
            })
        else:
            context.update({
                "selected_destination": selected_destination,
            })
        return context

    def get_success_url(self):
        if self.success_url:
            url = self.success_url % self.object.__dict__
        else:
            try:
                url = self.object.get_absolute_url(self.kwargs.get("destination_pk", False))
            except AttributeError:
                raise ImproperlyConfigured(
                    "No URL to redirect to.  Either provide a url or define"
                    " a get_absolute_url method on the Model.")
        return url


class JourneyDetailView(DetailView):
    model = Journey
    template_name = "journey_blog/journey/detail.html"
    context_object_name = "journey"

    def get_context_data(self, **kwargs):
        context = super(JourneyDetailView, self).get_context_data(**kwargs)
        destination_pk = self.kwargs.get("destination_pk", False)
        if destination_pk:
            selected_destination = JourneyDestination.objects.get(pk=destination_pk)
        elif self.object.destinations.count() > 0:
            selected_destination = self.object.destinations.first()
        else:
            selected_destination = False
        if selected_destination:
            context.update({
                "selected_destination": selected_destination,
            })
        else:
            context.update({
                "selected_destination": selected_destination,
            })
        return context

project/journey_blog/templates/journey_blog/journey/create.html
{% extends "journey_blog/base.html" %}
{% load i18n %}
{% block content %}
    <div id="create">
        <form action="{% url "journey_create" %}" method="post">
            {% csrf_token %}
            <h1>{% trans "Share your own journey" %}</h1>
            {{ form.title.label_tag }}
            {{ form.title }}
            {{ form.description.label_tag }}
            {{ form.description }}
            <button>{% trans "Start" %}</button>
        </form>
    </div>
{% endblock %}

project/journey_blog/templates/journey_blog/journey/detail.html
{% extends "journey_blog/base.html" %}
{% load i18n %}
{% block content %}
    <div id="editor">
        <header class="detail">
            <div class="actions left">
                <a class="abort" href="{% url "journey_list" %}">
                    {% trans "Close" %}
                </a>
                <a class="settings" href="#settings">
                    {% trans "Share" %}
                </a>
            </div>
            <h1>
                {{ journey.title }}
            </h1>
        </header>
        <aside class="detail">
            {% include "journey_blog/journey/includes/detail_destinations.html" %}
        </aside>
        <div class="update">
            <div class="content_container">
                {{ selected_destination.content|safe }}
            </div>
        </div>
    </div>
{% endblock %}

project/journey_blog/templates/journey_blog/journey/list.html
{% extends "journey_blog/base.html" %}
{% load i18n %}
{% block content %}
    <div id="editor">
        <header class="header_list">
            <nav>
                <ul>
                    <li>
                        <a href="{% url "about" %}">{% trans "About" %}</a>
                    </li>
                    <li>
                        <a href="{% url "tips_tricks" %}">{% trans "Tips & Tricks" %}</a>
                    </li>
                    <li>
                        <a href="{% url "experience" %}">{% trans "Experience" %}</a>
                    </li>
                    <li>
                        <a href="{% url "journey_list" %}">{% trans "Journeys" %}</a>
                    </li>
                </ul>
            </nav>
            <div class="actions right">
                {% if not journey.published %}
                <a href="#" class="login" data-action="login">
                    {% trans "Login" %}
                </a>
                {% endif %}
                <a href="#" class="passive register" data-action="register">
                    {% trans "Register" %}
                </a>
            </div>
        </header>
        <div class="list">
            <div class="list_frame">
                <div class="intro_header">
                    <ul>
                        <a href="{% url "journey_create" %}">{% trans "Share your own journey" %}</a>
                    </ul>
                </div>
                <ul class="list_journeys">
                    {% for journey in journeys %}
                        <li class="list_journeys_item">
                            <a href="{% url "journey_detail" journey.pk %}">
                                <h2>{{ journey.title }}</h2>
                                <p>{{ journey.description }}</p>
                                <ul>
                                    {% for destination in journey.destinations.all %}
                                        <li>{{ destination.name }}</li>
                                    {% endfor %}
                                </ul>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

project/journey_blog/templates/journey_blog/journey/update.html
{% extends "journey_blog/base.html" %}
{% load i18n %}
{% block content %}
    <div id="editor">
        <header>
            <div class="actions left">
                <a class="abort" href="{% url "journey_list" %}">
                    {% trans "Abort" %}
                </a>
                <a class="settings" href="#settings">
                    {% trans "Settings" %}
                </a>
            </div>
            <h1>
                {{ journey.title }}
            </h1>
            <div class="actions right">
                {% if not journey.published %}
                <button class="publish" data-action="publish">
                    {% trans "Publish" %}
                </button>
                {% endif %}
                <button class="passive save" data-action="save">
                    {% trans "Save" %}
                </button>
            </div>
        </header>
        <aside>
            {% include "journey_blog/journey/includes/update_destinations.html" %}
        </aside>
        <div class="update">
            {% if content_form %}
                <form id="content_editor" action="{% if selected_destination %}{% url "journey_update_destination" journey.pk selected_destination.pk %}{% else %}{% url "journey_update" journey.pk %}{% endif %}" method="post">
                    {% csrf_token %}
                    <input id="id_published" name="published" type="checkbox">
                    {{ content_form.name }}
                    {{ content_form.types }}
                    {{ content_form.content }}
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}